"""
Code Generator: Self-Modifying Code System

This module enables Paradma to:
1. Analyze learned patterns
2. Generate Python code for the algorithm
3. Write the code into native_operations.py
4. Reload the module to use the new implementation

TRUE META-PROGRAMMING: Paradma writes its own code!
"""

import typing as t
from pathlib import Path
import ast
import importlib


class CodeGenerator:
    """
    Generates Python code from learned patterns and writes it
    into Paradma's source files for true self-modification.
    """
    
    def __init__(self, target_file: str = None):
        if target_file is None:
            # Default: write to native_operations.py in the same directory
            self.target_file = Path(__file__).parent / "native_operations.py"
        else:
            self.target_file = Path(target_file)
        
        # Ensure the file exists with a header
        self._initialize_target_file()
    
    def _initialize_target_file(self):
        """Initialize the native operations file if it doesn't exist"""
        if not self.target_file.exists():
            header = '''"""
Native Operations: Auto-Generated by Paradma's Learning System

This file is AUTOMATICALLY GENERATED by the CodeGenerator.
Paradma writes its own implementations here after learning from NumPy.

DO NOT EDIT MANUALLY - This file is self-modifying!
Generated implementations are added dynamically as Paradma learns.
"""

# Auto-generated native implementations below:

'''
            self.target_file.write_text(header, encoding='utf-8')
    
    def generate_addition_code(self, observations: list) -> str:
        """
        Generate Python code for addition based on observations.
        Analyzes patterns and creates optimized implementation.
        """
        code = '''
def native_add(a, b):
    """
    Native addition implementation.
    Auto-generated by analyzing NumPy patterns.
    
    Supports:
    - Scalar addition: native_add(5, 3) -> 8
    - List addition: native_add([1,2], [3,4]) -> [4,6]
    - Array-like addition with broadcasting
    """
    # Handle scalar case
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a + b
    
    # Handle list/array case
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        # Element-wise addition
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and hasattr(y, '__iter__'):
                # Nested arrays
                result.append(native_add(x, y))
            else:
                result.append(x + y)
        return result
    
    # Broadcasting: scalar + array
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a + item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item + b for item in a]
    
    return a + b
'''
        return code
    
    def generate_multiply_code(self, observations: list) -> str:
        """Generate code for multiplication"""
        code = '''
def native_multiply(a, b):
    """
    Native multiplication implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Scalar multiplication
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a * b
    
    # Element-wise multiplication
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and hasattr(y, '__iter__'):
                result.append(native_multiply(x, y))
            else:
                result.append(x * y)
        return result
    
    # Broadcasting
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a * item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item * b for item in a]
    
    return a * b
'''
        return code
    
    def generate_dot_code(self, observations: list) -> str:
        """Generate code for dot product"""
        code = '''
def native_dot(a, b):
    """
    Native dot product implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Convert to lists if needed
    if not isinstance(a, (list, tuple)):
        a = [a]
    if not isinstance(b, (list, tuple)):
        b = [b]
    
    # Vector dot product: sum of element-wise products
    if len(a) != len(b):
        raise ValueError(f"Vectors must have same length: {len(a)} vs {len(b)}")
    
    result = 0
    for x, y in zip(a, b):
        result += x * y
    
    return result
'''
        return code
    
    def generate_matmul_code(self, observations: list) -> str:
        """Generate code for matrix multiplication"""
        code = '''
def native_matmul(a, b):
    """
    Native matrix multiplication implementation.
    Auto-generated by analyzing NumPy patterns.
    
    Implements the standard matrix multiplication algorithm:
    C[i,j] = sum(A[i,k] * B[k,j]) for all k
    """
    # Ensure we have 2D matrices
    if not isinstance(a, list):
        a = [[a]]
    elif not isinstance(a[0], list):
        a = [[x] for x in a]
    
    if not isinstance(b, list):
        b = [[b]]
    elif not isinstance(b[0], list):
        b = [[x] for x in b]
    
    rows_a = len(a)
    cols_a = len(a[0]) if a else 0
    rows_b = len(b)
    cols_b = len(b[0]) if b else 0
    
    if cols_a != rows_b:
        raise ValueError(
            f"Cannot multiply matrices with shapes "
            f"({rows_a}, {cols_a}) and ({rows_b}, {cols_b})"
        )
    
    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    
    # Perform matrix multiplication
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j] += a[i][k] * b[k][j]
    
    return result
'''
        return code
    
    def generate_sqrt_code(self, observations: list) -> str:
        """Generate code for square root using Newton's method"""
        code = '''
def native_sqrt(x):
    """
    Native square root implementation using Newton's method.
    Auto-generated by analyzing NumPy patterns.
    
    Newton's method: x_{n+1} = (x_n + S/x_n) / 2
    Converges quadratically to sqrt(S)
    """
    if x < 0:
        raise ValueError("Cannot compute square root of negative number")
    
    if x == 0:
        return 0.0
    
    if x == 1:
        return 1.0
    
    # Initial guess
    guess = x / 2.0
    
    # Newton's method iterations
    for _ in range(20):  # 20 iterations gives high precision
        new_guess = (guess + x / guess) / 2.0
        
        # Check for convergence
        if abs(new_guess - guess) < 1e-10:
            break
        
        guess = new_guess
    
    return guess
'''
        return code
    
    def generate_mean_code(self, observations: list) -> str:
        """Generate code for mean/average"""
        code = '''
def native_mean(arr):
    """
    Native mean (average) implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    if not hasattr(arr, '__iter__') or isinstance(arr, str):
        return arr  # Scalar case
    
    # Convert to flat list
    flat = list(arr)
    
    if len(flat) == 0:
        return 0.0
    
    total = sum(flat)
    count = len(flat)
    
    return total / count
'''
        return code
    
    def add_implementation(self, operation: str, observations: list):
        """
        Generate code for an operation and ADD it to the native_operations.py file.
        This is TRUE SELF-MODIFICATION!
        """
        # Map operation names to code generators
        generators = {
            'add': self.generate_addition_code,
            'multiply': self.generate_multiply_code,
            'dot': self.generate_dot_code,
            'matmul': self.generate_matmul_code,
            'sqrt': self.generate_sqrt_code,
            'mean': self.generate_mean_code,
        }
        
        if operation not in generators:
            raise ValueError(f"No code generator for operation: {operation}")
        
        # Generate the code
        generated_code = generators[operation](observations)
        
        # Read current file content
        current_content = self.target_file.read_text(encoding='utf-8')
        
        # Check if this operation already exists
        function_name = f"native_{operation}"
        if f"def {function_name}" in current_content:
            print(f"   [INFO] Function '{function_name}' already exists. Skipping.")
            return False
        
        # Add a separator and the new code
        separator = f"\n\n# {'='*60}\n# Auto-generated: {operation}\n# {'='*60}\n"
        new_content = current_content + separator + generated_code + "\n"
        
        # WRITE THE CODE TO THE FILE (SELF-MODIFICATION!)
        self.target_file.write_text(new_content, encoding='utf-8')
        
        print(f"   [CODE-GEN] Generated and wrote 'native_{operation}' to {self.target_file.name}")
        return True
    
    def get_native_implementation(self, operation: str) -> t.Callable:
        """
        Load the native implementation from the self-modified file.
        This dynamically imports the code we just generated!
        """
        # Import the module
        import native_operations
        
        # Reload to get the latest code
        importlib.reload(native_operations)
        
        # Get the function
        function_name = f"native_{operation}"
        if hasattr(native_operations, function_name):
            return getattr(native_operations, function_name)
        
        return None
