"""
Native Operations: Auto-Generated by Paradma's Learning System

This file is AUTOMATICALLY GENERATED by the CodeGenerator.
Paradma writes its own implementations here after learning from NumPy.

DO NOT EDIT MANUALLY - This file is self-modifying!
Generated implementations are added dynamically as Paradma learns.
"""

# Auto-generated native implementations below:



# ============================================================
# Auto-generated: sqrt
# ============================================================

def native_sqrt(x):
    """
    Native square root implementation using Newton's method.
    Auto-generated by analyzing NumPy patterns.
    """
    # Handle array-like input (element-wise)
    if hasattr(x, '__iter__') and not isinstance(x, str):
        return [native_sqrt(item) for item in x]

    if x < 0:
        raise ValueError("Cannot compute square root of negative number")
    
    if x == 0:
        return 0.0
    
    if x == 1:
        return 1.0
    
    # Initial guess
    guess = x / 2.0
    
    # Newton's method iterations
    for _ in range(20):  # 20 iterations gives high precision
        new_guess = (guess + x / guess) / 2.0
        
        # Check for convergence
        if abs(new_guess - guess) < 1e-10:
            break
        
        guess = new_guess
    
    return guess



# ============================================================
# Auto-generated: subtract
# ============================================================

def native_subtract(a, b):
    """
    Native subtraction implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Handle scalar case
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a - b
    
    # Handle list/array case
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        # Element-wise subtraction
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and not isinstance(x, str):
                result.append(native_subtract(x, y))
            else:
                result.append(x - y)
        return result
    
    # Broadcasting: scalar - array
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a - item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item - b for item in a]
    
    return a - b



# ============================================================
# Auto-generated: multiply
# ============================================================

def native_multiply(a, b):
    """
    Native multiplication implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Scalar multiplication
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a * b
    
    # Element-wise multiplication
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and not isinstance(x, str):
                result.append(native_multiply(x, y))
            else:
                result.append(x * y)
        return result
    
    # Broadcasting
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a * item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item * b for item in a]
    
    return a * b



# ============================================================
# Auto-generated: add
# ============================================================

def native_add(a, b):
    """
    Native addition implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Handle scalar case
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a + b
    
    # Handle list/array case
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        # Element-wise addition
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and not isinstance(x, str):
                result.append(native_add(x, y))
            else:
                result.append(x + y)
        return result
    
    # Broadcasting: scalar + array
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a + item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item + b for item in a]
    
    return a + b



# ============================================================
# Auto-generated: matmul
# ============================================================

def native_matmul(a, b):
    """
    Native matrix multiplication implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Ensure we have 2D matrices (convert from numpy or nested lists)
    def to_list_2d(m):
        if not hasattr(m, '__iter__') or isinstance(m, str):
            return [[m]]
        
        # Convert to list
        l = list(m)
        if not l:
            return [[]]
        
        if not hasattr(l[0], '__iter__') or isinstance(l[0], str):
            # 1D -> 2D (column vector)
            return [[x] for x in l]
        
        # Already 2D-ish
        return [list(row) for row in l]

    A = to_list_2d(a)
    B = to_list_2d(b)
    
    rows_a = len(A)
    cols_a = len(A[0]) if A else 0
    rows_b = len(B)
    cols_b = len(B[0]) if B else 0
    
    if cols_a != rows_b:
        raise ValueError(
            f"Cannot multiply matrices with shapes "
            f"({rows_a}, {cols_a}) and ({rows_b}, {cols_b})"
        )
    
    # Initialize result matrix with zeros
    result = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    
    # Perform matrix multiplication
    for i in range(rows_a):
        for j in range(cols_b):
            for k in range(cols_a):
                result[i][j] += A[i][k] * B[k][j]
    
    return result

