"""
Native Operations: Auto-Generated by Paradma's Learning System

This file is AUTOMATICALLY GENERATED by the CodeGenerator.
Paradma writes its own implementations here after learning from NumPy.

DO NOT EDIT MANUALLY - This file is self-modifying!
Generated implementations are added dynamically as Paradma learns.
"""

# Auto-generated native implementations below:



# ============================================================
# Auto-generated: add
# ============================================================

def native_add(a, b):
    """
    Native addition implementation.
    Auto-generated by analyzing NumPy patterns.
    
    Supports:
    - Scalar addition: native_add(5, 3) -> 8
    - List addition: native_add([1,2], [3,4]) -> [4,6]
    - Array-like addition with broadcasting
    """
    # Handle scalar case
    if not hasattr(a, '__iter__') or isinstance(a, str):
        if not hasattr(b, '__iter__') or isinstance(b, str):
            return a + b
    
    # Handle list/array case
    if hasattr(a, '__iter__') and hasattr(b, '__iter__'):
        # Element-wise addition
        result = []
        for x, y in zip(a, b):
            if hasattr(x, '__iter__') and hasattr(y, '__iter__'):
                # Nested arrays
                result.append(native_add(x, y))
            else:
                result.append(x + y)
        return result
    
    # Broadcasting: scalar + array
    if not hasattr(a, '__iter__') or isinstance(a, str):
        return [a + item for item in b]
    if not hasattr(b, '__iter__') or isinstance(b, str):
        return [item + b for item in a]
    
    return a + b



# ============================================================
# Auto-generated: dot
# ============================================================

def native_dot(a, b):
    """
    Native dot product implementation.
    Auto-generated by analyzing NumPy patterns.
    """
    # Convert to lists if needed
    if not isinstance(a, (list, tuple)):
        a = [a]
    if not isinstance(b, (list, tuple)):
        b = [b]
    
    # Vector dot product: sum of element-wise products
    if len(a) != len(b):
        raise ValueError(f"Vectors must have same length: {len(a)} vs {len(b)}")
    
    result = 0
    for x, y in zip(a, b):
        result += x * y
    
    return result



# ============================================================
# Auto-generated: sqrt
# ============================================================

def native_sqrt(x):
    """
    Native square root implementation using Newton's method.
    Auto-generated by analyzing NumPy patterns.
    
    Newton's method: x_{n+1} = (x_n + S/x_n) / 2
    Converges quadratically to sqrt(S)
    """
    if x < 0:
        raise ValueError("Cannot compute square root of negative number")
    
    if x == 0:
        return 0.0
    
    if x == 1:
        return 1.0
    
    # Initial guess
    guess = x / 2.0
    
    # Newton's method iterations
    for _ in range(20):  # 20 iterations gives high precision
        new_guess = (guess + x / guess) / 2.0
        
        # Check for convergence
        if abs(new_guess - guess) < 1e-10:
            break
        
        guess = new_guess
    
    return guess

